function dxdt = sys_h(x, u, prob_info)

L = 2; % length from rear wheel axle to the front axle

dxdt = [x(4,1)*cos(x(3,1)); ...
        x(4,1)*sin(x(3,1)); ...
        (x(4,1)/L)*tan(u(1,1));...
        u(2,1);...
        0.5*u(1,1)^2+0.5*u(2,1)^2];